version: "3.9"
services:
  myapp:
       image: erwanku/api_django_crud:v1.0
       ports:
         - 8000:8000
       networks:
         - mynetwork
  mydb:
      image: postgres:12.9-alpine3.15
      ports:
        - 5432:5432
      environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      volumes:
      - pgdata_volume:/var/lib/postgresql/data
      networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  pgdata_volume: